import type { Metadata } from "next";
import Navbar from "../shared/navbar";
import Footer from "../shared/footer";
import ScrollToTop from "../components/ScrollToTop";

export const metadata: Metadata = {
  title: "Haywhai Event-Booking",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="overflow-x-hidden">
      <Navbar/>
      {children}
      <Footer/>
        <ScrollToTop />
    </div>
  );
}
